# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        c3upo_provider:
            entity:
                class: AppBundle:LoginUser
                property: username

    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm:    bcrypt
            cost: 12
        AppBundle\Entity\LoginUser:
            algorithm:    bcrypt
            cost: 12     

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login_firewall:
            pattern:   ^/admin/login$
            anonymous: ~
            
        secured_area:
            pattern: ^/
            anonymous: ~
            provider: c3upo_provider
            form_login:
                login_path: login_route
                check_path: login_check
                default_target_path: admin_index
                always_use_default_target_path: true
            logout:
                path: logout
                target: login_route
            
    access_control:
        - { path: '^/registration', roles: IS_AUTHENTICATED_ANONYMOUSLY }        
#        - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/admin/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^/admin', roles: [ROLE_ADMIN] } 
#        - { path: '^/', roles: IS_AUTHENTICATED_ANONYMOUSLY } 
